### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by ppebay** [Pressio/pressio#16] opened 2019-10-10 08:39 UTC
The goal of this issue is to discuss Pressio testing and CI

**Comment by mperrinel** [comment] 2019-10-10 13:55
Is there a plan to do a CI for Pressio ? If it is, I suggest to start as soon as possible. Indeed it's safer to have a projet, even if it is small, that have a nightly build.

Remember that a CI have to do the following tasks : 
1. Install the projet every day for every targeted platform, compilers and configuration.
2. Run all the tests
3. Do the code coverage
4. Deploy and create different artefact / setup etc..
5. Automatically do all the build and tests when a PR is created.
6. Others communications with the GItlab.

**Comment by fnrizzi** [comment] 2019-10-10 17:52
@mperrinel thanks for the comment. 
A few things to reply: 
(a) yes, there is a plan for CI. Since I am currently changing the build system, I would like to wait for that to be over... (b) yes, I agree on the CI process. 

I see CI as a potential target for Q3 for FY20. But, I might have to choose between setting up CI and improving the tests themselves (i.e. what they test, the testing code itself, the policy on how to name them, etc.), I would choose the second. Reason is that a proper testing strategy/method/guidelines are always needed. CI is something that builds on top of that. 

Let's see how things evolve!

**Comment by fnrizzi** [comment] 2019-10-15 20:16
Tentative plan: 
* due Q1: decide where to setup CI and how to 
* due Q2: first version of CI up and running 
* due Q3: finalize CI such that it is maintainable and extendable

**Comment by mperrinel** [comment] 2019-10-16 09:03
Thanks for the plan.
From my recent experience on other projects, a real problem is to define where the CI will be installed. There is of course the possibility to use already some online platform like Gitlab with Gitlab-CI but most of them have some hard limitation (memory available, max number of builds, number of build in //, Compilation time limitation accessibility to different runners, CI specific features that could blocked quickly some of the features we plan to add, etc...).
If the plan is to create our CI instance (Jenkins, Gitlab-ci, etc..) it is very important to define as soon as possible where it will be installed.
Please tell me if you need first a quick analysis on a set of CI and their limitations on their online versions

**Comment by fnrizzi** [comment] 2019-10-16 09:17
yes! 
* it would be great to have a quick glance at free/online options ! 
* what did you use for the other projects? 
* I can explore options in-house without making names :)

**Comment by mperrinel** [comment] 2019-10-16 10:02
With NGA, I have already used Jenkins, and Gitlab-CI.
With gitlab-ci, I tried the online free version but was essentially blocked because of compilation time limitation (more than 3hours is not allowed) and runners times allowed (after a moment, you need to purchase time).
For the Jenkins and the Gitlab-ci, I used a custom installation on some machines (localhost of my Mac and localhost of an external and powerful machine).
One the installation is done, it is easy to configure the CI but with some limitations:
- My local machine doesn't have a lot of space and a lot of core available to compile
- My local machine cannot be used as the final solution for the CI
- The external machine is better but without a CI instance in production with a real web access, it's not the best option.

The best option is to have a dedicated and securised server.

I'll provide a quick glance for (Jenkins, Gitlab-CI, Travis, Circle-ci) on their free/online versions.
If you want to check another CI, let me know !

**Comment by fnrizzi** [comment] 2019-10-16 10:20
* I think I can find a server for this. Possibly with GPU too. so that is good. Let me look into it! 
* I would go for Jenkins, I used that before too. But am open to others. In my view, the simpler the better!

**Comment by mperrinel** [comment] 2019-10-16 12:36
Very goo new for the servers if you have one.
I'll do the quick glance with some additional info and we will see. Do you have an idea about all the targeted platforms and  compilers ?

**Comment by fnrizzi** [comment] 2019-10-16 12:41
not yet, but will make a list of that! 
If you have a default/basic list of compilers/platforms you use, let me know. We can use that to start with.

**Comment by mperrinel** [comment] 2019-10-16 13:13
That really depends of who will use the application : 
For a large public Windows and Mac are good.
For university people : Linux and Mac.
For specific people : HPC Platform ?

So what is the cross platform compatibility of your code.
For one of my other project, we have all the platform.
For another we have only Linux and Mac.

But in all the case, the CI could works on some different Linux distribution : Fedora, Ubuntu, Centos. It's more difficult to have a CI working on Mac and Windows because of their virtualisation and License.

For the compilers, we can start with the default one of their correspondant platform : 
Fedora : gcc@8.3.1
Ubuntu : gcc@7.4.0

But maybe you need also an Intel compiler ?

I know how to configure Gitlab-CI using docker to get an easy access to Linux platform and in fact any image you can find on the docker hun

For Jenkins, I never combined it with Jenkins but I know that Jenkins can do it of course.

**Comment by fnrizzi** [comment] 2019-10-16 13:19
ok, let me make a list and get back to you with specific ones!

**Comment by mperrinel** [comment] 2019-10-21 14:12
I finished my preliminary analysis on the CI discussed previously and my conclusions are :
- Jenkins can do the job but : 
  - We will have to chose between using docker or not.
  - Its configuration will have to be documented with a focus on its plugins used for the project.
- Gitlab-CI can be used if : 
  - We plan to switch the Ghitub project to a Gitlab project.
  - We plan to keep the Ghitub project but we can pay for a License.
- Travis can be used if :
  - We want to begin quickly a CI for the Pressio Github project.
  - We want an easy configuration.
  - Pressio won't need more than two hours to build.
  - Pressio won't need powerful resources to build.
- Circle-CI cannot be used : 
  - Indeed, it becomes interesting only if you can afford it.

Jenkins:
- Online version:  No
- Local version: Ok
  - Pricing: free
- Features: Anything with the help of plugins.
- Difficulty: A lot of plugins and their different versions which are not always easy to configure and could become a problem when moving from local instance to a dedicated server if the Jenkins itself is not the same.

Gitlab-CI:
- Online and local version:  Ok
  - Online pricing (Per user, per month): Free ($0), Bronze($4), Silver($19), Gold($99)
  - Local pricing (Per user, per month): Core ($0), Starter($4), Premium($19), Ultimate($99)
  - Note: the pricing is for a Gitlab License, not only the Gitlab-CI which is considered as a feature.
  - Link of the complete feature list: https://about.gitlab.com/features/
- Features (For free/core license): 
  - The Gitlab-CI feature is available and can be configured using a Pipeline written in a yaml file. Tests run distributed on separate machines of which you can add as many as you want. Each build can be split in multiple jobs that run in parallel on multiple machines. 
  - Docker is supported.
  - GitLab CI/CD for external repositories. Free until the March 22nd, 2020 (https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/). After that, a Premium or Silver license will be necessary.
- Difficulties: 
  - The Gitlab-CI is a part of a Gitlab project. In the case of a Github project, you can use the mirroring feature that allow to mirror a Ghitub project into Gitlab. Without the feature, the Gitlab project will only contains the CI yaml file and you will have to clone the real project and work with the Ghitub API direclty from your script.
  - Shared Runners pipeline minutes quota: 2000 minutes per group / per month. After that, you can buy some additional minutes
  - Shared Runners can be held up by another project’s jobs.
  - Shared Runners have a default time limitation of 3h per build and cannot be customized if you are not the owner of the Shared runners
  - Shared Runners cannot be configured if you are not the owner of the Shared runners (That means you need a local version)
  - Specfic Runners can be installed anywhere and register to the Gitlab-CI (local or online)
  - After the March 22nd, 2020, The CI will be free only for Gitlab project.
  - Note: A free alternative is to creake an empty Gitlab project with no source and to clone the external project as a first step direclty to the CI yaml script.

Travis
- Online and local version:  Ok
  - Pricing for business project: (unlimited collaborators, per month): Boostrap ($63), Startup($118), Small business ($228), Premium($448)
  - Pricing for open source project: Free
- Features (For free/core license): 
  - Quick setup for Github project
  - Travis CI account use you Github account and scan all of your Github project
  - Write your instruction into a .travis.yml file.
  - Lot of languages accepted
- Difficulties:
  - Build time limitation: 120 minutes per job
  - You have to use build matrix to split you task into different one of 120 minutes.

Circle-CI
- Online and local version:  Ok
  - Online Pricing: Free (Get 2500 credits per weeks), Performance (15$/month for the first 3 users, 15$/month for additional user), Custom (defined with the company).
  - Local pricing: $35/month per user with an annual plan.
- Features (Free License):
  - 1 Parallel job
  -  Linux, Windows	
- Difficulty (Free License):
  - Not macOS compatible
  - Only one parallel job for free
  - Don’t have access to large computer for performance

**Comment by fnrizzi** [comment] 2019-10-21 14:15
Thanks @mperrinel ! I will take a look soon!

**Comment by mperrinel** [comment] 2019-11-11 10:49
@fnrizzi @ppebay 
After some discussions with @fnrizzi, we have decided to start with Travis because : 

- Pression installation with its dependencies doesn't need more than a few minutes to build (less than 120 minutes)
- Pressio is completely open source which is the condition to use a free version of Travis
- Travis is already ready to use since we use the online version
- Travis is well known to have a good and easy connection with Github project
- Travis results are also public

**Comment by pressiotravis** [comment] 2019-11-13 14:02
@fnrizzi @ppebay 
A Travis CI configuration has been setting up here :
[Pressio CI](https://travis-ci.com/Pressio/pressio).
Currently the script is based on the Pressio build tutorial instructions but uses the latest version of Pressio instead of the v0.2.1 used by the instruction.

TODO: 

- @fnrizzi can verify if the current script is ok. 
- @fnrizzi can merge the CI script from master to develop
- @mperrinel can test trigger script rules (commit coming from develop, master, feature or PR)

**Comment by mperrinel** [comment] 2020-08-17 15:55
Travis is currently working correctly on this project.
Accordingly to @fnrizzi, the next step is to migrate the CI from Travis to GitHub Actions which is more Github friendly.

After a quick analysis of GitHub Actions, this is a set of some relevant points concerning the CI : 

- 2000 minutes per month on the free version
- Creation of the actions yml file inside : .github/workflows directory
- Can be branch specific
- By default jobs run in parallel
- Return code is crucial for each steps. 0 -> passed, none 0 -> rejected
- Github actions provides shared generic action:
    - example : actions/checkout@v1
        - checkout is the name of the action
        - v1 is the version you want to use for the action 
- Actions are available from the marketplace of GitHub

I'll create a branch for a test that reproduces the Travis script.

**Closed** 2022-08-28 12:12 UTC
Labels: question, unit testing
